---
version: "3.8"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    restart: always
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: 'changeme'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    volumes:
      - "etc_pihole:/etc/pihole/"
      - "etc_dnsmasq_d:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN

volumes:
  etc_pihole:
    external: false
  etc_dnsmasq_d:
    external: false
...
