---
version: "3.8"

services:
  beets:
    image: lscr.io/linuxserver/beets:arm32v7-latest
    container_name: beets
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "8337:8337"
    volumes:
      - "config:/config"
      - "/mnt/external/media/Music:/music"
      - "/home/pi/Downloads:/downloads"
    

volumes:
  config:
    external: false
...
