# -*- eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t); -*-
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Beets Docker-Compose
#+date: <2021-12-29 Wed>
#+author: Thomas Freeman
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.4.6)

* About
This org file is a literate programming file to generate a Docker Compose ~.yaml~ file that will run the Beets music library manager software.
** Running Beets
/Note:/ To run the Beets command line interface, use the following command:
#+begin_src shell
  docker exec -ti -u abc beets bash
#+end_src
This will run a bash shell in the beets container with user ~abc~.
* Docker Compose Template
Below is a template that will create the Docker Compose file:
#+begin_src yaml :noweb yes :tangle yes
  ---
  version: "3.8"
  
  services:
    <<service>>
      <<environment>>
      <<ports>>
      <<volumes>>
      <<cap_add>>
  
  <<create_volumes>>
  ...
#+end_src
* Declare Pi-hole Service
Create a service called ~beets~ that pulls the official Linuxserver.io Docker image for beets and always restarts when Docker restarts.
#+name: service
#+begin_src yaml
  beets:
    image: lscr.io/linuxserver/beets:arm32v7-latest
    container_name: beets
    restart: always
#+end_src
* Environment
Set the time zone and a user settings for Beets.
#+name: environment
#+begin_src yaml
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
#+end_src
* Published Ports
Use the default port setup for the Beets web UI.
#+name: ports
#+begin_src yaml
  ports:
    - "8337:8337"
#+end_src
* Volumes
The volume ~beets_config~ will be created to store configuration between updates. In addtion, Beets needs to be able to find where the music files in the music library can be found along with a location where downloaded or new music files can be imported from.
#+name: volumes
#+begin_src yaml
  volumes:
    - "config:/config"
    - "/mnt/external/media/Music:/music"
    - "/home/pi/Downloads:/downloads"
#+end_src
* Create Named Volumes
Beets configuration data in this compose file will be stored in a Docker named volume called ~beets_config~. Docker compose will automatically add the ~beets_~ prefix to the named volumes to prevent name conflict.
#+name: create_volumes
#+begin_src yaml
  volumes:
    config:
      external: false
#+end_src
