---
version: "3.8"

services:
  calibre-web:
    image: linuxserver/calibre-web:arm32v7-latest
    container_name: calibre-web
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "8083:8083"
    volumes:
      - "config:/config"
      - "/mnt/external/media/Library/Books:/books"

volumes:
  config:
    external: false      
...
