# -*- eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t); -*-
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Grocy Docker Compose
#+date: <2021-12-29 Wed>
#+author: Thomas Freeman
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.4.6)

* About
This org file is a literate programming file to generate a Docker Compose ~.yaml~ file that will run the Grocy service that can inventory your household grocery items.
* Docker Compose Template
Below is a template that will create the Docker Compose file:
#+begin_src yaml :noweb yes :tangle yes
  ---
  version: "3.8"
  
  services:
    <<service>>
      <<environment>>
      <<ports>>
      <<volumes>>
  
  <<create_volumes>>
  ...
#+end_src
* Declare Grocy Service
Create a service called ~grocy~ that pulls the Grocy image from linuxserver.io that always restarts the service if Docker restarts.
#+name: service
#+begin_src yaml
  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy
    restart: always
#+end_src
* Environment
Set Grocy to use the default user and group for the server along with the local time zone.
#+name: environment
#+begin_src yaml
  environment:
    - PUID=1000
    - PGID=1000
    - TZ=America/Chicago
#+end_src
* Published Ports
Set Grocy to use port 8080 instead of 80 to avoid conflict with Pi-hole service.
#+name: ports
#+begin_src yaml
  ports:
    - "8080:80"
#+end_src
* Volumes
The volume ~grocy_config~ will be created to store configuration between updates.
#+name: volumes
#+begin_src yaml
  volumes:
    - "config:/config"
#+end_src
* Create Named Volumes
Grocy configuration data in this compose file will be stored in a Docker named volume called ~grocy_config~ on the host system. Docker compose will automatically add the ~grocy_~ prefix to the named volume ~config~ in the example below to prevent name conflict.
#+name: create_volumes
#+begin_src yaml
  volumes:
    config:
      external: false      
#+end_src
