---
version: "3.8"

services:
  grocy:
    image: linuxserver/grocy:latest
    container_name: grocy
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - "8080:80"
    volumes:
      - "config:/config"

volumes:
  config:
    external: false      
...
