---
version: "3.8"

services:
  pihole:
    container_name: calibre
    image: linuxserver/calibre:arm32v7-arch
    restart: always
    environment:
      - PUID=1000
      - GUID=1000
      - TZ=America/Chicago
    ports:
      - "8082:8080"
      - "8084:8081"
    volumes:
      - "/mnt/external/media/Library/Books:/config"
    

volumes:
  config:
    external: false
...
