# -*- eval: (add-hook 'after-save-hook (lambda ()(org-babel-tangle)) nil t); -*-
#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:nil c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil f:t inline:t num:nil
#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t
#+options: timestamp:t title:t toc:t todo:t |:t
#+title: Calibre Docker Compose
#+date: <2021-12-29 Wed>
#+author: Thomas Freeman
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 27.1 (Org mode 9.4.6)

* About
This org file is a literate programming file to generate a Docker Compose ~.yaml~ file that will run the Calibre ebook library management suite.
* Docker Compose Template
Below is a template that will create the Docker Compose file:
#+begin_src yaml :noweb yes :tangle yes
  ---
  version: "3.8"
  
  services:
    <<service>>
      <<environment>>
      <<ports>>
      <<volumes>>
      <<cap_add>>
  
  <<create_volumes>>
  ...
#+end_src
* Declare Pi-hole Service
Create a service called ~calibre~ that pulls the official Linuxserver.io Docker image for Calibre and always restarts when Docker restarts.
#+name: service
#+begin_src yaml
  pihole:
    container_name: calibre
    image: linuxserver/calibre:arm32v7-arch
    restart: always
#+end_src
* Environment
Set the time zone and a user settings for Calibre.
#+name: environment
#+begin_src yaml
  environment:
    - PUID=1000
    - GUID=1000
    - TZ=America/Chicago
#+end_src
* Published Ports
Use the default port setup for Calibre
#+name: ports
#+begin_src yaml
  ports:
    - "8082:8080"
    - "8084:8081"
#+end_src
* Volumes
The volume ~calibre_config~ will be created to store configuration between updates.
#+name: volumes
#+begin_src yaml
  volumes:
    - "/mnt/external/media/Library/Books:/config"
#+end_src
* Create Named Volumes
Calibre configuration data in this compose file will be stored in a Docker named volume called ~calibre_config~. Docker compose will automatically add the ~calibre_~ prefix to the named volumes to prevent name conflict.
#+name: create_volumes
#+begin_src yaml
  volumes:
    config:
      external: false
#+end_src
