---
version: "3.8"

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    network_mode: host
    restart: always
    
    ports:
      - "8096:8096"
    volumes:
      - "config:/config"
      - "cache:/cache"
      - "/mnt/external/media:/media"

volumes:
  config:
    external: false
  cache:
    external: false
...
